// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated from markdown game table from: https://github.com/gamedig/node-gamedig/blob/HEAD/GAMES_LIST.md

module.exports = [
  { name: 'ARMA 2: Operation Arrowhead', value: 'a2oa', search: 'arma 2: operation arrowhead a2oa' },
  { name: 'ARMA: Armed Assault', value: 'aaa', search: 'arma: armed assault aaa' },
  { name: "America's Army: Proving Grounds", value: 'aapg', search: "america's army: proving grounds aapg" },
  { name: 'Abiotic Factor', value: 'abioticfactor', search: 'abiotic factor abioticfactor' },
  { name: 'Action: Source', value: 'actionsource', search: 'action: source actionsource' },
  { name: 'ARMA: Cold War Assault', value: 'acwa', search: 'arma: cold war assault acwa' },
  { name: 'Action Half-Life', value: 'ahl', search: 'action half-life ahl' },
  { name: 'Alien Arena', value: 'alienarena', search: 'alien arena alienarena' },
  { name: 'Alien Swarm', value: 'alienswarm', search: 'alien swarm alienswarm' },
  { name: "America's Army", value: 'americasarmy', search: "america's army americasarmy" },
  { name: "America's Army 2", value: 'americasarmy2', search: "america's army 2 americasarmy2" },
  { name: "America's Army 3", value: 'americasarmy3', search: "america's army 3 americasarmy3" },
  { name: 'Age of Chivalry', value: 'aoc', search: 'age of chivalry aoc' },
  { name: 'Age of Empires 2', value: 'aoe2', search: 'age of empires 2 aoe2' },
  { name: 'Ace of Spades Classic', value: 'aosc', search: 'ace of spades classic aosc' },
  { name: 'ARMA 2', value: 'arma2', search: 'arma 2 arma2' },
  { name: 'ARMA 3', value: 'arma3', search: 'arma 3 arma3' },
  { name: 'Armagetron Advanced', value: 'armagetronadvanced', search: 'armagetron advanced armagetronadvanced' },
  { name: 'ARMA: Reforger', value: 'armareforger', search: 'arma: reforger armareforger' },
  { name: 'ARMA: Resistance', value: 'armaresistance', search: 'arma: resistance armaresistance' },
  { name: 'Ark: Survival Ascended', value: 'asa', search: 'ark: survival ascended asa' },
  { name: 'Ark: Survival Evolved', value: 'ase', search: 'ark: survival evolved ase' },
  { name: "Arca Sim Racing '08", value: 'asr08', search: "arca sim racing '08 asr08" },
  { name: 'Assetto Corsa', value: 'assettocorsa', search: 'assetto corsa assettocorsa' },
  { name: 'Atlas', value: 'atlas', search: 'atlas atlas' },
  { name: 'Avorion', value: 'avorion', search: 'avorion avorion' },
  { name: 'Aliens versus Predator 2', value: 'avp2', search: 'aliens versus predator 2 avp2' },
  { name: 'Aliens vs. Predator 2010', value: 'avp2010', search: 'aliens vs. predator 2010 avp2010' },
  { name: "Baldur's Gate", value: 'baldursgate', search: "baldur's gate baldursgate" },
  { name: 'Ballistic Overkill', value: 'ballisticoverkill', search: 'ballistic overkill ballisticoverkill' },
  { name: 'Barotrauma', value: 'barotrauma', search: 'barotrauma barotrauma' },
  { name: 'Build and Shoot', value: 'bas', search: 'build and shoot bas' },
  { name: 'Base Defense', value: 'basedefense', search: 'base defense basedefense' },
  { name: 'Battalion 1944', value: 'battalion1944', search: 'battalion 1944 battalion1944' },
  { name: 'Battlefield 1942', value: 'battlefield1942', search: 'battlefield 1942 battlefield1942' },
  { name: 'Battlefield 2', value: 'battlefield2', search: 'battlefield 2 battlefield2' },
  { name: 'Battlefield 2142', value: 'battlefield2142', search: 'battlefield 2142 battlefield2142' },
  { name: 'Battlefield 3', value: 'battlefield3', search: 'battlefield 3 battlefield3' },
  { name: 'Battlefield 4', value: 'battlefield4', search: 'battlefield 4 battlefield4' },
  { name: 'Battlefield Hardline', value: 'battlefieldhardline', search: 'battlefield hardline battlefieldhardline' },
  { name: 'Battlefield Vietnam', value: 'battlefieldvietnam', search: 'battlefield vietnam battlefieldvietnam' },
  { name: 'Battlefield: Bad Company 2', value: 'bbc2', search: 'battlefield: bad company 2 bbc2' },
  { name: 'BeamMP (2021)', value: 'beammp', search: 'beammp (2021) beammp' },
  { name: 'Black Mesa', value: 'blackmesa', search: 'black mesa blackmesa' },
  { name: 'Blade Symphony', value: 'bladesymphony', search: 'blade symphony bladesymphony' },
  { name: 'BrainBread', value: 'brainbread', search: 'brainbread brainbread' },
  { name: 'BrainBread 2', value: 'brainbread2', search: 'brainbread 2 brainbread2' },
  { name: 'Breach', value: 'breach', search: 'breach breach' },
  { name: 'Breed', value: 'breed', search: 'breed breed' },
  { name: 'Brink', value: 'brink', search: 'brink brink' },
  { name: 'BROKE PROTOCOL', value: 'brokeprotocol', search: 'broke protocol brokeprotocol' },
  { name: 'CS2D', value: 'c2d', search: 'cs2d c2d' },
  { name: 'Commandos 3: Destination Berlin', value: 'c3db', search: 'commandos 3: destination berlin c3db' },
  { name: 'Command and Conquer: Renegade', value: 'cacr', search: 'command and conquer: renegade cacr' },
  { name: "Clive Barker's Undying", value: 'cbu', search: "clive barker's undying cbu" },
  { name: 'Chaser', value: 'chaser', search: 'chaser chaser' },
  { name: 'Chrome', value: 'chrome', search: 'chrome chrome' },
  { name: 'Chivalry: Medieval Warfare', value: 'cmw', search: 'chivalry: medieval warfare cmw' },
  { name: 'Call of Duty', value: 'cod', search: 'call of duty cod' },
  { name: 'Call of Duty 2', value: 'cod2', search: 'call of duty 2 cod2' },
  { name: 'Call of Duty 3', value: 'cod3', search: 'call of duty 3 cod3' },
  { name: 'Call of Duty 4: Modern Warfare', value: 'cod4mw', search: 'call of duty 4: modern warfare cod4mw' },
  { name: 'Call of Duty: Black Ops 3', value: 'codbo3', search: 'call of duty: black ops 3 codbo3' },
  { name: 'Codename CURE', value: 'codenamecure', search: 'codename cure codenamecure' },
  { name: 'Codename Eagle', value: 'codenameeagle', search: 'codename eagle codenameeagle' },
  { name: 'Call of Duty: Modern Warfare 2', value: 'codmw2', search: 'call of duty: modern warfare 2 codmw2' },
  { name: 'Call of Duty: Modern Warfare 3', value: 'codmw3', search: 'call of duty: modern warfare 3 codmw3' },
  { name: 'Call of Duty: United Offensive', value: 'coduo', search: 'call of duty: united offensive coduo' },
  { name: 'Call of Duty: World at War', value: 'codwaw', search: 'call of duty: world at war codwaw' },
  { name: 'Call of Juarez', value: 'coj', search: 'call of juarez coj' },
  { name: 'Colony Survival', value: 'colonysurvival', search: 'colony survival colonysurvival' },
  { name: 'Conan Exiles', value: 'conanexiles', search: 'conan exiles conanexiles' },
  { name: 'Contagion', value: 'contagion', search: 'contagion contagion' },
  { name: 'Contract J.A.C.K.', value: 'contractjack', search: 'contract j.a.c.k. contractjack' },
  { name: 'Core Keeper', value: 'corekeeper', search: 'core keeper corekeeper' },
  { name: 'Counter-Strike 1.5', value: 'counterstrike15', search: 'counter-strike 1.5 counterstrike15' },
  { name: 'Counter-Strike 1.6', value: 'counterstrike16', search: 'counter-strike 1.6 counterstrike16' },
  { name: 'Counter-Strike 2', value: 'counterstrike2', search: 'counter-strike 2 counterstrike2' },
  { name: 'Cross Racing Championship Extreme', value: 'crce', search: 'cross racing championship extreme crce' },
  { name: 'Creativerse', value: 'creativerse', search: 'creativerse creativerse' },
  { name: 'Crysis', value: 'crysis', search: 'crysis crysis' },
  { name: 'Crysis 2', value: 'crysis2', search: 'crysis 2 crysis2' },
  { name: 'Crysis Wars', value: 'crysiswars', search: 'crysis wars crysiswars' },
  { name: 'Counter-Strike: Condition Zero', value: 'cscz', search: 'counter-strike: condition zero cscz' },
  { name: 'Counter-Strike: Global Offensive', value: 'csgo', search: 'counter-strike: global offensive csgo' },
  { name: 'Counter-Strike: Source', value: 'css', search: 'counter-strike: source css' },
  { name: 'Double Action: Boogaloo', value: 'dab', search: 'double action: boogaloo dab' },
  { name: 'Daikatana', value: 'daikatana', search: 'daikatana daikatana' },
  { name: 'Dark and Light', value: 'dal', search: 'dark and light dal' },
  { name: 'Day of Dragons', value: 'dayofdragons', search: 'day of dragons dayofdragons' },
  { name: 'DayZ', value: 'dayz', search: 'dayz dayz' },
  { name: 'DayZ Mod', value: 'dayzmod', search: 'dayz mod dayzmod' },
  { name: 'Dino D-Day', value: 'ddd', search: 'dino d-day ddd' },
  { name: 'Deadly Dozen: Pacific Theater', value: 'ddpt', search: 'deadly dozen: pacific theater ddpt' },
  { name: 'Deathmatch Classic', value: 'deathmatchclassic', search: 'deathmatch classic deathmatchclassic' },
  { name: 'Deer Hunter 2005', value: 'deerhunter2005', search: 'deer hunter 2005 deerhunter2005' },
  { name: 'Descent 3', value: 'descent3', search: 'descent 3 descent3' },
  { name: 'Deus Ex', value: 'deusex', search: 'deus ex deusex' },
  { name: 'Devastation', value: 'devastation', search: 'devastation devastation' },
  { name: "Darkest Hour: Europe '44-'45", value: 'dhe4445', search: "darkest hour: europe '44-'45 dhe4445" },
  { name: 'Discord', value: 'discord', search: 'discord discord' },
  { name: 'Dark Messiah of Might and Magic', value: 'dmomam', search: 'dark messiah of might and magic dmomam' },
  { name: 'Duke Nukem Forever 2001', value: 'dnf2001', search: 'duke nukem forever 2001 dnf2001' },
  { name: 'Day of Defeat', value: 'dod', search: 'day of defeat dod' },
  { name: 'Day of Defeat: Source', value: 'dods', search: 'day of defeat: source dods' },
  { name: 'Day of Infamy', value: 'doi', search: 'day of infamy doi' },
  { name: 'Doom 3', value: 'doom3', search: 'doom 3 doom3' },
  { name: 'Drakan: Order of the Flame', value: 'dootf', search: 'drakan: order of the flame dootf' },
  { name: 'Dota 2', value: 'dota2', search: 'dota 2 dota2' },
  { name: 'Days of War', value: 'dow', search: 'days of war dow' },
  { name: "Don't Starve Together", value: 'dst', search: "don't starve together dst" },
  { name: 'Dirt Track Racing 2', value: 'dtr2', search: 'dirt track racing 2 dtr2' },
  { name: 'Dystopia', value: 'dystopia', search: 'dystopia dystopia' },
  { name: 'Eco', value: 'eco', search: 'eco eco' },
  { name: 'Empyrion - Galactic Survival', value: 'egs', search: 'empyrion - galactic survival egs' },
  { name: 'Halo Online - ElDewrito', value: 'eldewrito', search: 'halo online - eldewrito eldewrito' },
  { name: 'Empires Mod', value: 'empiresmod', search: 'empires mod empiresmod' },
  { name: 'enshrouded', value: 'enshrouded', search: 'enshrouded enshrouded' },
  { name: 'Enemy Territory: Quake Wars', value: 'etqw', search: 'enemy territory: quake wars etqw' },
  { name: 'Euro Truck Simulator 2', value: 'ets2', search: 'euro truck simulator 2 ets2' },
  { name: 'Exfil', value: 'exfil', search: 'exfil exfil' },
  { name: "F1 Challenge '99-'02", value: 'f1c9902', search: "f1 challenge '99-'02 f1c9902" },
  { name: 'Factorio', value: 'factorio', search: 'factorio factorio' },
  { name: 'Far Cry', value: 'farcry', search: 'far cry farcry' },
  { name: 'Far Cry 2', value: 'farcry2', search: 'far cry 2 farcry2' },
  { name: 'Farming Simulator 19', value: 'farmingsimulator19', search: 'farming simulator 19 farmingsimulator19' },
  { name: 'Farming Simulator 22', value: 'farmingsimulator22', search: 'farming simulator 22 farmingsimulator22' },
  { name: 'Farming Simulator 25', value: 'farmingsimulator25', search: 'farming simulator 25 farmingsimulator25' },
  { name: 'F.E.A.R.', value: 'fear', search: 'f.e.a.r. fear' },
  { name: 'Frontlines: Fuel of War', value: 'ffow', search: 'frontlines: fuel of war ffow' },
  { name: 'Fistful of Frags', value: 'fof', search: 'fistful of frags fof' },
  { name: 'Formula One 2002', value: 'formulaone2002', search: 'formula one 2002 formulaone2002' },
  { name: 'Fortress Forever', value: 'fortressforever', search: 'fortress forever fortressforever' },
  { name: 'FOUNDRY', value: 'foundry', search: 'foundry foundry' },
  { name: "Garry's Mod", value: 'garrysmod', search: "garry's mod garrysmod" },
  { name: 'Giants: Citizen Kabuto', value: 'gck', search: 'giants: citizen kabuto gck' },
  { name: 'Geneshift', value: 'geneshift', search: 'geneshift geneshift' },
  { name: 'Global Operations', value: 'globaloperations', search: 'global operations globaloperations' },
  { name: 'GoldenEye: Source', value: 'goldeneyesource', search: 'goldeneye: source goldeneyesource' },
  { name: 'Ground Breach', value: 'groundbreach', search: 'ground breach groundbreach' },
  { name: 'Grand Theft Auto V - alt:V Multiplayer', value: 'gta5am', search: 'grand theft auto v - alt:v multiplayer gta5am' },
  { name: 'Grand Theft Auto V - FiveM', value: 'gta5f', search: 'grand theft auto v - fivem gta5f' },
  { name: 'Grand Theft Auto V - RageMP', value: 'gta5r', search: 'grand theft auto v - ragemp gta5r' },
  { name: 'Grand Theft Auto: San Andreas Multiplayer', value: 'gtasam', search: 'grand theft auto: san andreas multiplayer gtasam' },
  { name: 'Grand Theft Auto: San Andreas - Multi Theft Auto', value: 'gtasamta', search: 'grand theft auto: san andreas - multi theft auto gtasamta' },
  { name: 'Grand Theft Auto: San Andreas OpenMP', value: 'gtasao', search: 'grand theft auto: san andreas openmp gtasao' },
  { name: 'Grand Theft Auto: Vice City - Multi Theft Auto', value: 'gtavcmta', search: 'grand theft auto: vice city - multi theft auto gtavcmta' },
  { name: 'Gunman Chronicles', value: 'gunmanchronicles', search: 'gunman chronicles gunmanchronicles' },
  { name: 'Gore: Ultimate Soldier', value: 'gus', search: 'gore: ultimate soldier gus' },
  { name: 'Halo', value: 'halo', search: 'halo halo' },
  { name: 'Halo 2', value: 'halo2', search: 'halo 2 halo2' },
  { name: 'Hawakening', value: 'hawakening', search: 'hawakening hawakening' },
  { name: 'Heretic II', value: 'heretic2', search: 'heretic ii heretic2' },
  { name: 'Hexen II', value: 'hexen2', search: 'hexen ii hexen2' },
  { name: 'Hidden & Dangerous 2', value: 'hiddendangerous2', search: 'hidden & dangerous 2 hiddendangerous2' },
  { name: 'Half-Life 2: Deathmatch', value: 'hl2d', search: 'half-life 2: deathmatch hl2d' },
  { name: 'Half-Life Deathmatch', value: 'hld', search: 'half-life deathmatch hld' },
  { name: 'Half-Life Deathmatch: Source', value: 'hlds', search: 'half-life deathmatch: source hlds' },
  { name: 'Hell Let Loose', value: 'hll', search: 'hell let loose hll' },
  { name: 'Half-Life: Opposing Force', value: 'hlof', search: 'half-life: opposing force hlof' },
  { name: 'Homefront', value: 'homefront', search: 'homefront homefront' },
  { name: 'Homeworld 2', value: 'homeworld2', search: 'homeworld 2 homeworld2' },
  { name: 'Hurtworld', value: 'hurtworld', search: 'hurtworld hurtworld' },
  { name: 'IGI 2: Covert Strike', value: 'i2cs', search: 'igi 2: covert strike i2cs' },
  { name: 'IL-2 Sturmovik', value: 'i2s', search: 'il-2 sturmovik i2s' },
  { name: 'Icarus', value: 'icarus', search: 'icarus icarus' },
  { name: 'Insurgency: Modern Infantry Combat', value: 'imic', search: 'insurgency: modern infantry combat imic' },
  { name: 'Insurgency', value: 'insurgency', search: 'insurgency insurgency' },
  { name: 'Insurgency: Sandstorm', value: 'insurgencysandstorm', search: 'insurgency: sandstorm insurgencysandstorm' },
  { name: 'Iron Storm', value: 'ironstorm', search: 'iron storm ironstorm' },
  { name: 'James Bond 007: Nightfire', value: 'jb0n', search: 'james bond 007: nightfire jb0n' },
  { name: 'Just Cause 2 - Multiplayer', value: 'jc2m', search: 'just cause 2 - multiplayer jc2m' },
  { name: 'Just Cause 3 - Multiplayer', value: 'jc3m', search: 'just cause 3 - multiplayer jc3m' },
  { name: 'Killing Floor', value: 'killingfloor', search: 'killing floor killingfloor' },
  { name: 'Killing Floor 2', value: 'killingfloor2', search: 'killing floor 2 killingfloor2' },
  { name: 'Kingpin: Life of Crime', value: 'kloc', search: 'kingpin: life of crime kloc' },
  { name: 'Kiss: Psycho Circus: The Nightmare Child', value: 'kpctnc', search: 'kiss: psycho circus: the nightmare child kpctnc' },
  { name: 'Kreedz Climbing', value: 'kreedzclimbing', search: 'kreedz climbing kreedzclimbing' },
  { name: 'Kerbal Space Program - DMP', value: 'kspd', search: 'kerbal space program - dmp kspd' },
  { name: 'Left 4 Dead', value: 'l4d', search: 'left 4 dead l4d' },
  { name: 'Left 4 Dead 2', value: 'l4d2', search: 'left 4 dead 2 l4d2' },
  { name: 'Mafia II - Multiplayer', value: 'm2m', search: 'mafia ii - multiplayer m2m' },
  { name: 'Mafia II - Online', value: 'm2o', search: 'mafia ii - online m2o' },
  { name: 'Minecraft: Bedrock Edition', value: 'mbe', search: 'minecraft: bedrock edition mbe' },
  { name: 'Medieval Engineers', value: 'medievalengineers', search: 'medieval engineers medievalengineers' },
  { name: 'Mumble - GT Murmur', value: 'mgm', search: 'mumble - gt murmur mgm' },
  { name: 'Minecraft', value: 'minecraft', search: 'minecraft minecraft' },
  { name: 'Minetest', value: 'minetest', search: 'minetest minetest' },
  { name: 'Monday Night Combat', value: 'mnc', search: 'monday night combat mnc' },
  { name: 'Myth of Empires', value: 'moe', search: 'myth of empires moe' },
  { name: 'Medal of Honor', value: 'moh', search: 'medal of honor moh' },
  { name: 'Medal of Honor: Airborne', value: 'moha', search: 'medal of honor: airborne moha' },
  { name: 'Medal of Honor: Allied Assault', value: 'mohaa', search: 'medal of honor: allied assault mohaa' },
  { name: 'Medal of Honor: Allied Assault Breakthrough', value: 'mohaab', search: 'medal of honor: allied assault breakthrough mohaab' },
  { name: 'Medal of Honor: Allied Assault Spearhead', value: 'mohaas', search: 'medal of honor: allied assault spearhead mohaas' },
  { name: 'Medal of Honor: Pacific Assault', value: 'mohpa', search: 'medal of honor: pacific assault mohpa' },
  { name: 'Medal of Honor: Warfighter', value: 'mohw', search: 'medal of honor: warfighter mohw' },
  { name: 'Mordhau', value: 'mordhau', search: 'mordhau mordhau' },
  { name: 'Mumble', value: 'mumble', search: 'mumble mumble' },
  { name: 'Mutant Factions', value: 'mutantfactions', search: 'mutant factions mutantfactions' },
  { name: 'Nerf Arena Blast', value: 'nab', search: 'nerf arena blast nab' },
  { name: 'NASCAR Thunder 2004', value: 'nascarthunder2004', search: 'nascar thunder 2004 nascarthunder2004' },
  { name: 'Natural Selection', value: 'naturalselection', search: 'natural selection naturalselection' },
  { name: 'Natural Selection 2', value: 'naturalselection2', search: 'natural selection 2 naturalselection2' },
  { name: 'netPanzer', value: 'netpanzer', search: 'netpanzer netpanzer' },
  { name: 'Neverwinter Nights', value: 'neverwinternights', search: 'neverwinter nights neverwinternights' },
  { name: 'Neverwinter Nights 2', value: 'neverwinternights2', search: 'neverwinter nights 2 neverwinternights2' },
  { name: 'Nexuiz', value: 'nexuiz', search: 'nexuiz nexuiz' },
  { name: 'Need for Speed: Hot Pursuit 2', value: 'nfshp2', search: 'need for speed: hot pursuit 2 nfshp2' },
  { name: 'Nitro Family', value: 'nitrofamily', search: 'nitro family nitrofamily' },
  { name: 'Nova-Life: Amboise', value: 'nla', search: 'nova-life: amboise nla' },
  { name: 'No More Room in Hell', value: 'nmrih', search: 'no more room in hell nmrih' },
  { name: "No One Lives Forever 2: A Spy in H.A.R.M.'s Way", value: 'nolf2asihw', search: "no one lives forever 2: a spy in h.a.r.m.'s way nolf2asihw" },
  { name: 'Nuclear Dawn', value: 'nucleardawn', search: 'nuclear dawn nucleardawn' },
  { name: 'Operation Flashpoint: Cold War Crisis', value: 'ofcwc', search: 'operation flashpoint: cold war crisis ofcwc' },
  { name: 'Operation Flashpoint: Resistance', value: 'ofr', search: 'operation flashpoint: resistance ofr' },
  { name: 'Operation: Harsh Doorstop', value: 'ohd', search: 'operation: harsh doorstop ohd' },
  { name: 'Onset', value: 'onset', search: 'onset onset' },
  { name: 'OpenArena', value: 'openarena', search: 'openarena openarena' },
  { name: 'OpenTTD', value: 'openttd', search: 'openttd openttd' },
  { name: 'Painkiller', value: 'painkiller', search: 'painkiller painkiller' },
  { name: 'Palworld', value: 'palworld', search: 'palworld palworld' },
  { name: 'Primal Carnage: Extinction', value: 'pce', search: 'primal carnage: extinction pce' },
  { name: 'PixARK', value: 'pixark', search: 'pixark pixark' },
  { name: 'Postal 2', value: 'postal2', search: 'postal 2 postal2' },
  { name: 'Post Scriptum', value: 'postscriptum', search: 'post scriptum postscriptum' },
  { name: 'Project Reality: Battlefield 2', value: 'prb2', search: 'project reality: battlefield 2 prb2' },
  { name: 'Prey', value: 'prey', search: 'prey prey' },
  { name: 'Project Cars', value: 'projectcars', search: 'project cars projectcars' },
  { name: 'Project Cars 2', value: 'projectcars2', search: 'project cars 2 projectcars2' },
  { name: 'Project Zomboid', value: 'projectzomboid', search: 'project zomboid projectzomboid' },
  { name: 'Pirates, Vikings, and Knights II', value: 'pvak2', search: 'pirates, vikings, and knights ii pvak2' },
  { name: 'Quake 3: Arena', value: 'q3a', search: 'quake 3: arena q3a' },
  { name: 'Quake', value: 'quake', search: 'quake quake' },
  { name: 'Quake 2', value: 'quake2', search: 'quake 2 quake2' },
  { name: 'Quake 4', value: 'quake4', search: 'quake 4 quake4' },
  { name: 'Quake Live', value: 'quakelive', search: 'quake live quakelive' },
  { name: 'Rainbow Six', value: 'rainbowsix', search: 'rainbow six rainbowsix' },
  { name: 'RalliSport Challenge', value: 'rallisportchallenge', search: 'rallisport challenge rallisportchallenge' },
  { name: 'Rally Masters', value: 'rallymasters', search: 'rally masters rallymasters' },
  { name: 'Rag Doll Kung Fu', value: 'rdkf', search: 'rag doll kung fu rdkf' },
  { name: 'Red Dead Redemption 2 - RedM', value: 'rdr2r', search: 'red dead redemption 2 - redm rdr2r' },
  { name: 'Redline', value: 'redline', search: 'redline redline' },
  { name: 'Red Orchestra', value: 'redorchestra', search: 'red orchestra redorchestra' },
  { name: 'Red Orchestra 2', value: 'redorchestra2', search: 'red orchestra 2 redorchestra2' },
  { name: 'Renegade X', value: 'renegade10', search: 'renegade x renegade10' },
  { name: 'Renown', value: 'renown', search: 'renown renown' },
  { name: 'rFactor', value: 'rfactor', search: 'rfactor rfactor' },
  { name: 'rFactor 2', value: 'rfactor2', search: 'rfactor 2 rfactor2' },
  { name: 'Ricochet', value: 'ricochet', search: 'ricochet ricochet' },
  { name: 'Rising World', value: 'risingworld', search: 'rising world risingworld' },
  { name: 'Rise of Nations', value: 'ron', search: 'rise of nations ron' },
  { name: 'Red Orchestra: Ostfront 41-45', value: 'roo4145', search: 'red orchestra: ostfront 41-45 roo4145' },
  { name: 'Risk of Rain 2', value: 'ror2', search: 'risk of rain 2 ror2' },
  { name: 'Rainbow Six 2: Rogue Spear', value: 'rs2rs', search: 'rainbow six 2: rogue spear rs2rs' },
  { name: 'Rising Storm 2: Vietnam', value: 'rs2v', search: 'rising storm 2: vietnam rs2v' },
  { name: 'Rainbow Six 3: Raven Shield', value: 'rs3rs', search: 'rainbow six 3: raven shield rs3rs' },
  { name: 'Return to Castle Wolfenstein', value: 'rtcw', search: 'return to castle wolfenstein rtcw' },
  { name: 'Rune', value: 'rune', search: 'rune rune' },
  { name: 'Rust', value: 'rust', search: 'rust rust' },
  { name: 'Savage 2: A Tortured Soul', value: 's2ats', search: 'savage 2: a tortured soul s2ats' },
  { name: 'Satisfactory', value: 'satisfactory', search: 'satisfactory satisfactory' },
  { name: '7 Days to Die', value: 'sdtd', search: '7 days to die sdtd' },
  { name: 'Serious Sam', value: 'serioussam', search: 'serious sam serioussam' },
  { name: 'Serious Sam 2', value: 'serioussam2', search: 'serious sam 2 serioussam2' },
  { name: 'Shattered Horizon', value: 'shatteredhorizon', search: 'shattered horizon shatteredhorizon' },
  { name: 'Shogo', value: 'shogo', search: 'shogo shogo' },
  { name: 'Shootmania', value: 'shootmania', search: 'shootmania shootmania' },
  { name: 'SiN', value: 'sin', search: 'sin sin' },
  { name: 'SiN Episodes', value: 'sinepisodes', search: 'sin episodes sinepisodes' },
  { name: 'Soldier of Fortune', value: 'sof', search: 'soldier of fortune sof' },
  { name: 'Soldier of Fortune 2', value: 'sof2', search: 'soldier of fortune 2 sof2' },
  { name: 'Soldat', value: 'soldat', search: 'soldat soldat' },
  { name: 'Sons Of The Forest', value: 'sotf', search: 'sons of the forest sotf' },
  { name: 'Soulmask', value: 'soulmask', search: 'soulmask soulmask' },
  { name: 'Space Engineers', value: 'spaceengineers', search: 'space engineers spaceengineers' },
  { name: 'Squad', value: 'squad', search: 'squad squad' },
  { name: 'SCP: Secret Labratory', value: 'ssl', search: 'scp: secret labratory ssl' },
  { name: 'Serious Sam: The Second Encounter', value: 'sstse', search: 'serious sam: the second encounter sstse' },
  { name: 'S.T.A.L.K.E.R.', value: 'stalker', search: 's.t.a.l.k.e.r. stalker' },
  { name: 'Starbound', value: 'starbound', search: 'starbound starbound' },
  { name: 'StarMade', value: 'starmade', search: 'starmade starmade' },
  { name: 'Starsiege', value: 'starsiege', search: 'starsiege starsiege' },
  { name: 'Star Trek: Bridge Commander', value: 'stbc', search: 'star trek: bridge commander stbc' },
  { name: 'Survive the Nights', value: 'stn', search: 'survive the nights stn' },
  { name: 'Star Trek: Voyager - Elite Force', value: 'stvef', search: 'star trek: voyager - elite force stvef' },
  { name: 'Star Trek: Voyager - Elite Force 2', value: 'stvef2', search: 'star trek: voyager - elite force 2 stvef2' },
  { name: 'Suicide Survival', value: 'suicidesurvival', search: 'suicide survival suicidesurvival' },
  { name: 'Sven Coop', value: 'svencoop', search: 'sven coop svencoop' },
  { name: 'SWAT 4', value: 'swat4', search: 'swat 4 swat4' },
  { name: 'Star Wars: Battlefront', value: 'swb', search: 'star wars: battlefront swb' },
  { name: 'Star Wars: Battlefront 2', value: 'swb2', search: 'star wars: battlefront 2 swb2' },
  { name: 'Star Wars Jedi Knight II: Jedi Outcast', value: 'swjk2jo', search: 'star wars jedi knight ii: jedi outcast swjk2jo' },
  { name: 'Star Wars Jedi Knight: Jedi Academy', value: 'swjkja', search: 'star wars jedi knight: jedi academy swjkja' },
  { name: 'Star Wars: Republic Commando', value: 'swrc', search: 'star wars: republic commando swrc' },
  { name: 'Synergy', value: 'synergy', search: 'synergy synergy' },
  { name: 'Tribes 1: Starsiege', value: 't1s', search: 'tribes 1: starsiege t1s' },
  { name: 'Tactical Ops', value: 'tacticalops', search: 'tactical ops tacticalops' },
  { name: "Tom Clancy's Ghost Recon Advanced Warfighter", value: 'tcgraw', search: "tom clancy's ghost recon advanced warfighter tcgraw" },
  { name: "Tom Clancy's Ghost Recon Advanced Warfighter 2", value: 'tcgraw2', search: "tom clancy's ghost recon advanced warfighter 2 tcgraw2" },
  { name: 'Team Factor', value: 'teamfactor', search: 'team factor teamfactor' },
  { name: 'Team Fortress 2', value: 'teamfortress2', search: 'team fortress 2 teamfortress2' },
  { name: 'Teamspeak 2', value: 'teamspeak2', search: 'teamspeak 2 teamspeak2' },
  { name: 'Teamspeak 3', value: 'teamspeak3', search: 'teamspeak 3 teamspeak3' },
  { name: 'Terminus', value: 'terminus', search: 'terminus terminus' },
  { name: 'Terraria - TShock', value: 'terrariatshock', search: 'terraria - tshock terrariatshock' },
  { name: 'Team Fortress Classic', value: 'tfc', search: 'team fortress classic tfc' },
  { name: 'The Forest', value: 'theforest', search: 'the forest theforest' },
  { name: 'The Front', value: 'thefront', search: 'the front thefront' },
  { name: 'The Hidden', value: 'thehidden', search: 'the hidden thehidden' },
  { name: 'The Isle', value: 'theisle', search: 'the isle theisle' },
  { name: 'The Ship', value: 'theship', search: 'the ship theship' },
  { name: 'The Specialists', value: 'thespecialists', search: 'the specialists thespecialists' },
  { name: "Tony Hawk's Pro Skater 3", value: 'thps3', search: "tony hawk's pro skater 3 thps3" },
  { name: "Tony Hawk's Pro Skater 4", value: 'thps4', search: "tony hawk's pro skater 4 thps4" },
  { name: "Tony Hawk's Underground 2", value: 'thu2', search: "tony hawk's underground 2 thu2" },
  { name: 'The Isle Evrima', value: 'tie', search: 'the isle evrima tie' },
  { name: 'Take On Helicopters', value: 'toh', search: 'take on helicopters toh' },
  { name: 'The Operative: No One Lives Forever', value: 'tonolf', search: 'the operative: no one lives forever tonolf' },
  { name: 'Tower Unite', value: 'towerunite', search: 'tower unite towerunite' },
  { name: 'TOXIKK', value: 'toxikk', search: 'toxikk toxikk' },
  { name: 'Trackmania 2', value: 'trackmania2', search: 'trackmania 2 trackmania2' },
  { name: 'Trackmania Forever', value: 'trackmaniaforever', search: 'trackmania forever trackmaniaforever' },
  { name: 'Tremulous', value: 'tremulous', search: 'tremulous tremulous' },
  { name: 'Tribes: Vengeance', value: 'tribesvengeance', search: 'tribes: vengeance tribesvengeance' },
  { name: 'Tron 2.0', value: 'tron20', search: 'tron 2.0 tron20' },
  { name: 'Turok 2', value: 'turok2', search: 'turok 2 turok2' },
  { name: 'Unreal 2: The Awakening - XMP', value: 'u2tax', search: 'unreal 2: the awakening - xmp u2tax' },
  { name: 'Universal Combat', value: 'universalcombat', search: 'universal combat universalcombat' },
  { name: 'Unreal', value: 'unreal', search: 'unreal unreal' },
  { name: 'Unreal Tournament', value: 'unrealtournament', search: 'unreal tournament unrealtournament' },
  { name: 'Unreal Tournament 2003', value: 'unrealtournament2003', search: 'unreal tournament 2003 unrealtournament2003' },
  { name: 'Unreal Tournament 2004', value: 'unrealtournament2004', search: 'unreal tournament 2004 unrealtournament2004' },
  { name: 'Unreal Tournament 3', value: 'unrealtournament3', search: 'unreal tournament 3 unrealtournament3' },
  { name: 'unturned', value: 'unturned', search: 'unturned unturned' },
  { name: 'Urban Terror', value: 'urbanterror', search: 'urban terror urbanterror' },
  { name: 'V8 Supercar Challenge', value: 'v8sc', search: 'v8 supercar challenge v8sc' },
  { name: 'Valheim', value: 'valheim', search: 'valheim valheim' },
  { name: 'Vampire Slayer', value: 'vampireslayer', search: 'vampire slayer vampireslayer' },
  { name: 'Vice City Multiplayer', value: 'vcm', search: 'vice city multiplayer vcm' },
  { name: 'Ventrilo', value: 'ventrilo', search: 'ventrilo ventrilo' },
  { name: 'Vietcong', value: 'vietcong', search: 'vietcong vietcong' },
  { name: 'Vietcong 2', value: 'vietcong2', search: 'vietcong 2 vietcong2' },
  { name: 'Vintage Story', value: 'vintagestory', search: 'vintage story vintagestory' },
  { name: 'V Rising', value: 'vrising', search: 'v rising vrising' },
  { name: 'Warfork', value: 'warfork', search: 'warfork warfork' },
  { name: 'Warsow', value: 'warsow', search: 'warsow warsow' },
  { name: 'Wolfenstein: Enemy Territory', value: 'wet', search: 'wolfenstein: enemy territory wet' },
  { name: 'Wolfenstein', value: 'wolfenstein', search: 'wolfenstein wolfenstein' },
  { name: 'World Of Padman', value: 'wop', search: 'world of padman wop' },
  { name: 'Wheel of Time', value: 'wot', search: 'wheel of time wot' },
  { name: 'Wurm Unlimited', value: 'wurmunlimited', search: 'wurm unlimited wurmunlimited' },
  { name: 'Xonotic', value: 'xonotic', search: 'xonotic xonotic' },
  { name: 'Xpand Rally', value: 'xpandrally', search: 'xpand rally xpandrally' },
  { name: 'Zombie Master', value: 'zombiemaster', search: 'zombie master zombiemaster' },
  { name: 'Zombie Panic: Source', value: 'zps', search: 'zombie panic: source zps' },
];
